services:
  db:
    container_name: shared_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  rabbitmq:
    container_name: shared_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  
  redis:
    container_name: shared_redis
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db_data:
  bundle_cache:
  rabbitmq_data:
  redis_data:
